
[opener]
edit = [
    { run = 'nvim "$@"', block = true, for = "unix" },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
open = [
    { run = 'xdg-open "$@"', desc = "Open" },
    # { run = 'okular "$@"', desc = "Open with okular" },
]

[open]
prepend_rules = [
    # Archive
    { mime = "application/xz", use = [ "extract", "reveal" ] },
]
rules = [
    { name = "*.html", use = [ "open", "edit" ] },
    { mime = "text/*", use = "edit" },
    { name = "*.log", use = "edit" },
    { mime = "application/json", use = "edit" },
    { mime = "video/*", use = "play" },
    { mime = "image/*", use = "open" },
    { mime = "application/pdf", use = "open" },
    { mime = "application/*sheet", use = "open" },
    { mime = "application/*excel", use = "open" },
]
append_rules = [
    { name = "*", use = "open" },
]

[manager]
linemode = "size"

[plugin]
prepend_previewers = [
    # Kernel Objects(driver)
    { name = "*.ko", run = "modinfo" },
]
