#!/bin/sh

export ZDOTDIR=~/.config/zsh

# some useful options (man zshoptions)
setopt nomatch
setopt auto_cd              # Automatically cd into typed directory.
setopt auto_list
setopt extendedglob
setopt hist_ignore_dups     # Dont store same command in history
setopt appendhistory        # Will be helpful if multiple settions are open
setopt interactive_comments
# setopt menucomplete
stty stop undef		        # Disable ctrl-s to freeze terminal.
zle_highlight=('paste:none')

# beeping is annoying
unsetopt BEEP

# completions
autoload -Uz compinit
zstyle ':completion:*' menu select completer _expand _complete _ignored
zmodload zsh/complist
# compinit
_comp_options+=(globdots)		# Include hidden files.

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# Colors
autoload -Uz colors && colors

# Useful Functions
source "$ZDOTDIR/zsh-functions"

# Normal files to source
zsh_add_file "zsh-vim-mode"
zsh_add_file "zsh-exports"
zsh_add_file "zsh-aliases"
zsh_add_file "zsh-prompt"

# Plugins
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "hlissner/zsh-autopair"
zsh_add_completion "esc/conda-zsh-completion" false

# Key-bindings
bindkey -s '^n' 'nvim $(fzf)^M'
bindkey '^[[P' delete-char
# bindkey "^p" up-line-or-beginning-search # Up
# bindkey "^n" down-line-or-beginning-search # Down
# bindkey "^k" up-line-or-beginning-search # Up
# bindkey "^j" down-line-or-beginning-search # Down

# Move with ctrl + arrows
bindkey '^[[1;5C' forward-word          # ctrl right arrow
bindkey '^[[1;5D' backward-word         # ctrl left arrow
bindkey '^H'      backward-delete-word  # ctrl Backspace
bindkey '^[[3;5~' delete-word           # ctrl Delete
bindkey '^[[3;~'  delete-char           # ctrl Delete
bindkey '^L'      clear-screen          # ctrl Shift L
bindkey '^K'      run-help              # eg. foo --> man foo

# Edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

# Open File Manager in current directory
bindkey -s '^@' 'ranger^M'

# Search packages in Package manager
bindkey -s '^p' 'pacinstall^M'
bindkey -s '^y' 'yayinstall^M'
bindkey -s '^a' 'aptinstall^M'

# ROS Melodic Specific
[ -f /opt/ros/melodic/setup.zsh ] && \
    source /opt/ros/melodic/setup.zsh && \
    source ~/catkin_ws/devel/setup.zsh

# Use lf to switch directories and bind it to ctrl-o
bindkey -s '^o' 'lfcd^M'

# bindkey -s '^a' 'bc -lq^M'
bindkey -s '^f' 'cd "$(dirname "$(fzf)")"^M'

compinit

