#!/bin/sh

# some useful options (man zshoptions)
setopt nomatch
setopt auto_cd              # Automatically cd into typed directory.
setopt auto_list
setopt extendedglob
setopt hist_ignore_dups     # Dont store same command in history
setopt appendhistory        # Will be helpful if multiple settions are open
setopt interactive_comments
# setopt menucomplete
stty stop undef		        # Disable ctrl-s to freeze terminal.
zle_highlight=('paste:none')

# beeping is annoying
unsetopt BEEP


# completions
autoload -Uz compinit
zstyle ':completion:*' menu select completer _expand _complete _ignored
zmodload zsh/complist
# compinit
_comp_options+=(globdots)		# Include hidden files.

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# Colors
autoload -Uz colors && colors

# Useful Functions
source "$ZDOTDIR/zsh-functions"

# Normal files to source
zsh_add_file "zsh-vim-mode"
zsh_add_file "zsh-exports"
zsh_add_file "zsh-aliases"
zsh_add_file "zsh-prompt"

# Plugins
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "hlissner/zsh-autopair"
zsh_add_completion "esc/conda-zsh-completion" false

# Key-bindings
bindkey -s '^n' 'nvim $(fzf)^M'
bindkey -s '^v' 'nvim\n'
bindkey '^[[P' delete-char
bindkey "^p" up-line-or-beginning-search # Up
bindkey "^n" down-line-or-beginning-search # Down
bindkey "^k" up-line-or-beginning-search # Up
bindkey "^j" down-line-or-beginning-search # Down
bindkey -r "^u"
bindkey -r "^d"

# Move with ctrl + arrows
bindkey '^[[1;5C' forward-word          # ctrl right arrow
bindkey '^[[1;5D' backward-word         # ctrl left arrow
bindkey '^H'      backward-delete-word  # ctrl Backspace
bindkey '^[[3;5~' delete-word           # ctrl Delete
bindkey '^[[3;~'  delete-char           # ctrl Delete
bindkey '^L'      clear-screen          # ctrl Shift L
bindkey '^K'      run-help              # eg. foo --> man foo

# Edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

# Open File Manager in current directory
bindkey -s '^@' 'ranger^M'

# Search packages in Package manager
bindkey -s '^p' 'pacinstall^M'
bindkey -s '^y' 'yayinstall^M'


# ROS Melodic Specific
[ -f /opt/ros/melodic/setup.zsh ] && \
    source /opt/ros/melodic/setup.zsh && \
    source ~/catkin_ws/devel/setup.zsh

# Use lf to switch directories and bind it to ctrl-o
lfcd () {
    tmp="$(mktemp)"
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp" >/dev/null
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}
bindkey -s '^o' 'lfcd^M'
bindkey -s '^a' 'bc -lq^M'
bindkey -s '^f' 'cd "$(dirname "$(fzf)")"^M'

# FZF
[ -f /usr/share/fzf/completion.zsh ] && source /usr/share/fzf/completion.zsh
[ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# [ -f $ZDOTDIR/completion/_fnm ] && fpath+="$ZDOTDIR/completion/"
# export FZF_DEFAULT_COMMAND='rg --hidden -l ""'
compinit

